# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workspaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wname', models.CharField(max_length=200, unique=True)),
                ('nemail', models.CharField(blank=True, max_length=200)),
                ('email1', models.CharField(blank=True, max_length=200)),
                ('email2', models.CharField(blank=True, max_length=200)),
                ('email3', models.CharField(blank=True, max_length=200)),
                ('email4', models.CharField(blank=True, max_length=200)),
                ('email5', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
