# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestedmailids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mailid', models.CharField(max_length=200, unique=True)),
                ('requester', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
