# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_requestedmailids'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedmailids',
            name='wname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
