# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_requestedmailids_wname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedmailids',
            name='mailid',
            field=models.CharField(max_length=200),
        ),
    ]
