# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-01 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_workspaces_adminmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('wname', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=1200)),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
