# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-01 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=150),
        ),
    ]
