# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20181201_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
