# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20181201_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='newchannels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channelname', models.CharField(blank=True, max_length=200)),
                ('wname', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
