# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-12 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_newchannels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newchannels',
            old_name='channelname',
            new_name='cname',
        ),
    ]
