# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20181212_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=500)),
                ('disc', models.CharField(blank=True, max_length=5000)),
                ('deadline', models.DateField(blank=True)),
                ('wname', models.CharField(max_length=200)),
                ('adminmail', models.CharField(blank=True, max_length=200)),
                ('nemail', models.CharField(blank=True, max_length=200)),
                ('email1', models.CharField(blank=True, max_length=200)),
                ('email2', models.CharField(blank=True, max_length=200)),
                ('email3', models.CharField(blank=True, max_length=200)),
                ('email4', models.CharField(blank=True, max_length=200)),
                ('email5', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
